// Generated by delombok at Sat Mar 04 13:21:18 CET 2023
package de.disk0.dbutil.impl.micrometer;

import java.time.Duration;

public interface MicrometerAdapter {
	void record(Duration duration, String metricName, Tag... tags);


	final class Tag {
		private final String key;
		private final String value;

		public static Tag of(String key, String value) {
			return new Tag(key, value);
		}

		@java.lang.SuppressWarnings("all")
		public Tag(final String key, final String value) {
			this.key = key;
			this.value = value;
		}

		@java.lang.SuppressWarnings("all")
		public String getKey() {
			return this.key;
		}

		@java.lang.SuppressWarnings("all")
		public String getValue() {
			return this.value;
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public boolean equals(final java.lang.Object o) {
			if (o == this) return true;
			if (!(o instanceof MicrometerAdapter.Tag)) return false;
			final MicrometerAdapter.Tag other = (MicrometerAdapter.Tag) o;
			final java.lang.Object this$key = this.getKey();
			final java.lang.Object other$key = other.getKey();
			if (this$key == null ? other$key != null : !this$key.equals(other$key)) return false;
			final java.lang.Object this$value = this.getValue();
			final java.lang.Object other$value = other.getValue();
			if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
			return true;
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public int hashCode() {
			final int PRIME = 59;
			int result = 1;
			final java.lang.Object $key = this.getKey();
			result = result * PRIME + ($key == null ? 43 : $key.hashCode());
			final java.lang.Object $value = this.getValue();
			result = result * PRIME + ($value == null ? 43 : $value.hashCode());
			return result;
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "MicrometerAdapter.Tag(key=" + this.getKey() + ", value=" + this.getValue() + ")";
		}
	}
}
